name: Build and publish package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'The new version number'
        required: false

env:
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  DOTNET_VERSION: '8.0.203' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGETTOKEN }} 
       
      - name: Build project
        working-directory: ./CsvHelper.FastDynamic
        run: dotnet build --configuration Release

      - name: Generate a NuGet package
        working-directory: ./CsvHelper.FastDynamic
        run: dotnet pack --no-build -c Release -p:PackageID=Plumsail.CsvHelper.FastDynamic -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --version-suffix ci${{ github.run_id }} -o .

      - name: Show some info
        working-directory: ./CsvHelper.FastDynamic
        run: |
            pwd
            ls -lha
            dotnet nuget list source

      - name: Push to GitHub package registry
        working-directory: ./CsvHelper.FastDynamic
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_AUTH_TOKEN --skip-duplicate    
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGETTOKEN }} 
        